### ISSUE TITLE
ETH México roadmap 

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/Turista-Mundial#1]
Backend
- [x] RPC and web3 setup
- [x] wallet connect setup
- [x] Hardhat setup

Frontend
- [x] create next app
- [x] tailwind setup
- [x] app router

Lens API
- [x] Login
- [x] Post
- [ ] Collect 

Smart contracts
- [x] Tourista Mundial contract
- [ ] Supertoken for superfluid

User interface
- [x] connect buttons (wallet &lens) 
- [x] locked screen 
- [x] unlocked screen
- [ ] new trip screen
- [ ] my trips screen
- [ ] current trips screen
- [ ] past trip screen
- [x] Frens trips screen
- [ ] Leaderboard

ETH México submission
- [x] Readme 
- [x] Backgrounds for video
- [x]  Logo
- [x]  3 snapshots
- [x]  4 Minutes video
- [x]  Fill project submission on the dashboard
- [x]  🏁 Submit the project and choose the judging time🏁
